### ISSUE TITLE
Exit code 1 for passed specs

### ISSUE THREAD

**Issue by brbrr** [rspec/rspec-core#2342] opened 2016-10-24 10:13 UTC
After `bundle update` my tests start to return exit code 1 for passed specs. 
```
brbrr$ MNZ_ENV=dev bundle exec rspec spec -t ~failing
# logs here
Finished in 12 minutes 46 seconds (files took 1.72 seconds to load)
409 examples, 0 failures

brbrr$ echo $?
1
```

My dependencies are:
```
  spec.add_dependency 'rake', '~> 11.2.0'
  spec.add_dependency 'rspec', '~> 3.5'
  spec.add_dependency 'rest-client'
  spec.add_dependency 'oauth', '~> 0.5.1'
  spec.add_dependency 'pry'
  spec.add_dependency 'oily_png'
  spec.add_dependency 'mysql2'
  spec.add_dependency 'allure-rspec', '~> 0.7.7'
  spec.add_dependency 'net-ssh'
```

And when I run only `:smoke` specs - I got correct 0 exit code. 
`brbrr$ MNZ_ENV=dev bundle exec rspec spec -t smoke -t ~failing`

**Comment by JonRowe** [comment] 2016-10-24 10:22
It's likely one of your dependencies is adding an `at_exit` hook and overriding the return status.

**Comment by myronmarston** [comment] 2016-10-24 16:51
@JonRowe's idea is definitely a good possible root cause but there are others.  Whatever the cause is, it's something in your environment, not something intrinsic to RSpec itself (we all have projects where rspec runs successfully and exits with `0`, so it's not a general RSpec problem).  Something in your environment is either directly causing this or is interacting with RSpec in a weird way to cause it.  Regardless, without more information, there's nothing we can do about this.  If you can pair this down to a reproducible example (preferably one that runs in less than 12 minutes...we don't have the time to debug such a slow test suite) we can try take a look.  That said, in these situations, usually the exercise of trying to pair it down to something reproducible surfaces the issue so I suspect if you go through the exercise of pairing it down you'll be able to find it yourself.

Closing, but feel free to continue the conversation.

**Closed by myronmarston** 2016-10-24 16:51 UTC
