### ISSUE TITLE
`match_array` not using proper item equality check (3.3.0)

### ISSUE THREAD

**Issue by ahorner** [rspec/rspec-core#1995] opened 2015-06-12 21:16 UTC
After upgrading to 3.3.0, I started seeing a handful of consistent spec failures.

- Installed through `rspec-rails` version 3.3.0
- Rails version 4.2.1
- Using `infer_spec_type_from_file_location!`

```
Failure/Error: expect(cart.remove_entry(line_item.id)).to match_array([line_item])
        expected collection contained:  [#<OrderLineItem id: 272, order_id: 300, unit_price_cents: 2, quantity: #<BigDecimal:7fbf32f3f338,'0.1E1',9(27)>, created_at: "2015-06-12 21:07:45", updated_at: "2015-06-12 21:07:45", price_book_entry_id: 460, discount_code_used: nil, position: 2, hidden: false>]
        actual collection contained:    [#<OrderLineItem id: 272, order_id: 300, unit_price_cents: 2, quantity: #<BigDecimal:7fbf334d8c90,'0.1E1',9(18)>, created_at: "2015-06-12 21:07:45", updated_at: "2015-06-12 21:07:45", price_book_entry_id: 460, discount_code_used: nil, position: 2, hidden: false>]
        the missing elements were:      [#<OrderLineItem id: 272, order_id: 300, unit_price_cents: 2, quantity: #<BigDecimal:7fbf32f3f338,'0.1E1',9(27)>, created_at: "2015-06-12 21:07:45", updated_at: "2015-06-12 21:07:45", price_book_entry_id: 460, discount_code_used: nil, position: 2, hidden: false>]
        the extra elements were:        [#<OrderLineItem id: 272, order_id: 300, unit_price_cents: 2, quantity: #<BigDecimal:7fbf334d8c90,'0.1E1',9(18)>, created_at: "2015-06-12 21:07:45", updated_at: "2015-06-12 21:07:45", price_book_entry_id: 460, discount_code_used: nil, position: 2, hidden: false>]
      # ./spec/models/cart_spec.rb:144:in `block (4 levels) in <top (required)>'
```

**Comment by myronmarston** [comment] 2015-06-12 22:08
Any chance you could put together a reproducible example for this?

Thanks!

**Comment by myronmarston** [comment] 2015-06-13 07:44
FWIW, I tried to repro with this:

``` ruby
user = User.create!(name: 'foo')
reloaded = User.find(user.id)

expect([user]).to match_array([reloaded])
```

...and it passes just fine.  There's got to be something different about your case, but I have no way to guess what it is :(.

**Comment by ahorner** [comment] 2015-06-13 17:19
The only thing that _might_ be different would be the fact that quantity is a decimal, loaded into the object as a `BigDecimal`, which you can see in my example results in different object IDs for that attribute on each record.

**Comment by cupakromer** [comment] 2015-06-13 18:31
I'm not sure that `BigDecimal` is an issue. The object ids won't affect it. The precision between the two values is a little different, but unless the values that are stored required the larger of the precisions the two `BigDecimal` instances will be equal.

Can you share your `remove_entry` method? It is important to understand what is happening under the hood.

I was thinking that it was possible that the timestamps are at fault. However, if these are `ActiveRecord` instances, their equality is simply based on their `id` values. What is potentially happening is that something is mutating either object state between the expectation check and the description being formatted. I would need to know what `remove_entry` does to understand what it's true object type is.

**Comment by ahorner** [comment] 2015-06-14 02:20
Turns out the issue is that the returned `OrderLineItem` is actually wrapped in another object:

```ruby
class LineItemBundle < DelegateClass(OrderLineItem)
```

In 3.3.0, the `contains_exactly` matcher appears to have reversed the order in which object equality is assessed, which is why these specs started failing:

```
[1] pry(main)> line_item = OrderLineItem.first
  OrderLineItem Load (8.6ms)  SELECT  "order_line_items".* FROM "order_line_items"  ORDER BY "order_line_items"."id" ASC LIMIT 1
=> #<OrderLineItem:0x007f9cec6cedb0 id: 1, ...>
[2] pry(main)> LineItemBundle.new(line_item) == line_item
=> true
[3] pry(main)> line_item == LineItemBundle.new(line_item)
=> false
```

We can work around the issue now that we know what it is, but it's a little unintuitive that equality seems to be evaluated in reverse order of written expectation.

**Comment by cupakromer** [comment] 2015-06-14 04:05
@ahorner thank you for that details :blue_heart: I have reproduced the issue. Though I haven't been able to narrow down the cause.

**Can you let me know which version you upgraded from?**

**Comment by ahorner** [comment] 2015-06-14 04:24
I originally attempted to upgrade directly from 3.2.0, but have confirmed that the issue is not present in 3.2.3.

**Comment by cupakromer** [comment] 2015-06-14 04:53
Thanks! :heart: I'll have to start digging further.

Currently, I'm not sure I see a regression here, at least not yet. From your description it seems a :bug: was fixed with the `contains_exactly` matcher :smile_cat:; though I do not see a cursory explanation for the change based on that matcher's history :grimacing:. It is possible updates across some of our repos have created a regression, but without a repo scenario based on a prior RSpec version, it will be difficult to track down.

I've looked at the current behavior and we may need to update some docs to explain it a bit more. Please let me know if the following makes sense or seems odd to you:

- given we have the following classes:

  ```ruby
  Widget         = Struct.new(:name)
  WidgetDelegate = Class.new(DelegateClass(Widget))
  ```
- the same widget is equal to itself

  ```ruby
  a_widget = Widget.new("Any Name")
  a_widget == a_widget
  # => true
  a_widget === a_widget
  # => true
  ```
- since `Struct` equality is based on the equality of all member attributes, two widgets with the same attributes are equal:

  ```ruby
  some_widget    = Widget.new("Matching Specific Name")
  another_widget = Widget.new("Matching Specific Name")
  some_widget == another_widget
  # => true
  some_widget === another_widget
  # => true
  another_widget == some_widget
  # => true
  another_widget === some_widget
  # => true
  ```
- by default a Ruby object (at least in 2.2) has four "equality" checks:
  - [`Object#===`](http://ruby-doc.org/core-2.2.2/Object.html#method-i-3D-3D-3D) (also called "case equality" or "match equality")

    > Case Equality – For class `Object`, effectively the same as calling `#==`, but typically overridden by descendants to provide meaningful semantics in `case` statements.
  - [`BasicObject#==`](http://ruby-doc.org/core-2.2.2/BasicObject.html#method-i-3D-3D)

      > Equality — At the `Object` level, `==` returns `true` only if `obj` and `other` are the same object. Typically, this method is overridden in descendant classes to provide class-specific meaning.
  - [`Object#eql?`](http://ruby-doc.org/core-2.2.2/Object.html#method-i-eql-3F)

    > The `eql?` method returns `true` if `obj` and `other` refer to the same hash key. This is used by `Hash` to test members for equality. For objects of class `Object`, `eql?` is synonymous with `==`. Subclasses normally continue this tradition by aliasing `eql?` to their overridden `==` method, but there are exceptions. `Numeric` types, for example, perform type conversion across `==`, but not across `eql?`
  - [`BasicObject#equal?`](http://ruby-doc.org/core-2.2.2/BasicObject.html#method-i-equal-3F)

    > Unlike `==`, the `equal?` method should never be overridden by subclasses as it is used to determine object identity (that is, `a.equal?(b)` if and only if `a` is the same object as `b`)
- in the case of an expectation: `expect(actual_object).to eq(expected_object)`

  Language parsing rules dictate that the above expression states the "authoritative" source on equality is the `expected_object`. Thus we can use the earlier objects and see:

  ```ruby
  a_widget   = Widget.new("Any Name")
  a_delegate = WidgetDelegate.new(a_widget)
  a_widget == a_delegate
  # => false
  a_widget === a_delegate
  # => false
  a_delegate == a_widget
  # => true
  a_delegate === a_widget
  # => true

  a_widget.class
  => Widget
  a_delegate.class
  => WidgetDelegate
  ```

  When we use the `a_widget` as the "authoritative" source, the equality checks fail. This happens because, even though the struct `Widget` has overridden `==` to match based on equal member attributes, it still expects equality based on the object type. Since the `a_widget` and `a_delegate` types do not match the check fails.

  If we make `a_delegate` the "authoritative" source, the checks pass. This is because the delegate passes the `==` and `===` messages to the underlying `Widget` object. Thus `a_delegate == a_widget` turns into `a_widget == a_widget`. Since the two objects are the same type and have the same attributes (in face in this instance they are the same object), the checks pass.

Based on the above behavior, I would assume that if:

```ruby
expect(a_delegate).to eq(a_widget)
```

does not pass (it does not). Then both of the following should also not pass (they do not):

```ruby
expect([a_delegate]).to contain_exactly([a_widget])
expect([a_delegate]).to match_array([a_widget])
```

**Comment by myronmarston** [comment] 2015-06-14 04:53
In general, we expect `==` to be symmetric, so that `(a == b) == (b == a)`.  To the extent that objects follow this, it shouldn't matter whether we check `actual == expected` or `expected == actual`.

We intentionally changed it from `actual == expected` to `expected == actual` for 3.3 in response to issues opened by users.  The specific change was here:

https://github.com/rspec/rspec-support/pull/193

This solved a specific issue multiple users ran into where objects with buggy `==` definition were passed to RSpec and would blow up.  It's a common mistake to define `==` like this:

``` ruby
class Color
  attr_reader :r, :g, :b

  def initialize(r, g, b)
    @r, @g, @b = r, g, b
  end

  def ==(other)
    other.r == r && other.g == g && other.b == b
  end
end
```

With this kind of definition `Color#==` works properly against other `Color` instances but raises errors when given _any other kind of object_, when it should return `false` for such situations.  When users do that they would get confusing errors that look liked they happened in RSpec when they did simple things like:

``` ruby
expect(display).to receive(:change_color).with(anything)
display.change_color(Color.new(10, 10, 10))
```

...because we were calling `actual == expected` (e.g. `Color#==(anything)`).  Switching to `expected == anything` fixed this problem.  See rspec/rspec-mocks#923 and rspec/rspec-expectations#732 for examples of reports from users about these problems.

I'm sorry that our bug fix for others caused this problem for you :(.  I didn't expect it -- as I said, we expect `==` to be symmetric, and as long as that's followed, our switch shouldn't affect anyone.

In this particular case, the non-symmetry of `==` is coming from a the ruby stdlib (`DelegateClass`) so there's not much you or us can do about that :(.

So I'm not really sure what, if anything we should do about this.

**Comment by cupakromer** [comment] 2015-06-14 04:58
:smile_cat: @myronmarston thanks for identify the root change

**Comment by cupakromer** [comment] 2015-06-14 05:46
> In this particular case, the non-symmetry of == is coming from a the ruby stdlib (DelegateClass) so there's not much you or us can do about that :(.

@ahorner I'm going to hazard a guess that you own both `LineItemBundle` and `OrderLineItem` definitions. While possibly not the most ideal options I see two things you could do to change the equality behavior (using my code sample from above):

- Implement a custom equality check using message passing so that delegators can intercept:

  ```ruby
  Widget = Struct.new(:name) do
    def ==(other)
      other.kind_of?(self.class) && name == other.name
    end
  end

  WidgetDelegate = Class.new(DelegateClass(Widget)) do
    def initialize(obj)
      @obj = obj
      super
    end

    def kind_of?(klass)
      @obj.kind_of?(klass)
    end
    alias_method :is_a?, :kind_of?
  end

  expect(a_widget).to eq a_delegate                   # pass
  expect(a_widget).to match a_delegate                # pass
  expect(a_delegate).to eq a_widget                   # pass
  expect(a_delegate).to match a_widget                # pass
  expect([a_delegate]).to match_array [a_widget]      # pass
  expect([a_delegate]).to contain_exactly a_widget    # pass
  ```
- Implement a custom conversion method:

  ```ruby
  Widget = Struct.new(:name) do
    def ==(other)
      super || (
        other.respond_to?(:to_widget) && other == self
      )
    end

    def to_widget
      self
    end
  end

  WidgetDelegate = Class.new(DelegateClass(Widget)) do
    def initialize(obj)
      @obj = obj
      super
    end

    def to_widget
      @obj
    end
  end

  expect(a_widget).to eq a_delegate                   # pass
  expect(a_widget).to match a_delegate                # pass
  expect(a_delegate).to eq a_widget                   # pass
  expect(a_delegate).to match a_widget                # pass
  expect([a_delegate]).to match_array [a_widget]      # pass
  expect([a_delegate]).to contain_exactly a_widget    # pass
  ```

**Comment by JonRowe** [comment] 2015-06-15 11:03
I think this is just the flip side of the issue we attempt to solve by flipping `actual == expected`, this is still a "buggy" `#==` operator

**Comment by myronmarston** [comment] 2015-06-15 15:09
> I think this is just the flip side of the issue we attempt to solve by flipping `actual == expected`, this is still a "buggy" `#==` operator

Yep, that's basically what I said above.  Problem is, the "buggy" `#==` definition comes from the ruby stdlib and is intentional, I believe.  After all, `DelegateClass` and `SimpleDelegator` are designed to proxy all their methods to the wrapped object...so `==` is proxied, too.

**Comment by ahorner** [comment] 2015-06-15 16:45
I think at this point I would be satisfied with updating the object description in the spec output to reflect the delegator's class. My confusion originally came from the fact that it wasn't obvious at all that a delegator was involved (probably due to `#inspect` also being delegated).

**Comment by myronmarston** [comment] 2015-06-15 17:11
> I think at this point I would be satisfied with updating the object description in the spec output to reflect the delegator's class. My confusion originally came from the fact that it wasn't obvious at all that a delegator was involved (probably due to `#inspect` also being delegated).

Do you have specific output in mind for this situation?

**Comment by ahorner** [comment] 2015-06-15 18:36
To handle the case of nested delegators, and also maintain information about the underlying item's actual class, something like the following might be appropriate:

```ruby
def description(object)
  if object.respond_to?(:__getobj__)
    delegated_class = object.__getobj__.class
    description(object.__getobj__).sub(delegated_class.to_s, "#{object.class}:#{delegated_class}")
  else
    object.inspect
  end
end
```

```
> description(OrderLineItem.first)
=> "#<OrderLineItem id: 1, ...>"
> description(LineItemBundle.new(OrderLineItem.first))
=> "#<LineItemBundle:OrderLineItem id: 1, ...>"
> description(LineItemBundle.new(OtherDelegator.new(OrderLineItem.first)))
=> "#<LineItemBundle:OtherDelegator:OrderLineItem id: 1, ...>"
```

I'm completely open to feedback on this. If people think it's a good idea, I can open a PR to fit it into the existing object description code.

**Comment by myronmarston** [comment] 2015-06-16 06:27
I think it's worth doing, although I think I might prefer it formatting something like:

``` irb
> description(LineItemBundle.new(OrderLineItem.first))
=> "#<LineItemBundle(#<OrderLineItem id: 1, ...>)>"
```

Essentially using parens to "wrap" the inner `inspect` just like the delegator wraps the object.

Here's where this would go:

https://github.com/rspec/rspec-support/blob/master/lib/rspec/support/object_formatter.rb

Closing here since there's nothing actionable to do in rspec-core.

**Closed by myronmarston** 2015-06-16 06:27 UTC

**Comment by mockdeep** [comment] 2015-06-16 16:28
We just ran into this, too. We've got a class `Status` where we've overridden the `==` operator so that we can compare against a string like `status == 'submitted'`. It actually feels a little dirty to me to monkey patch `String` to mirror it, though.

```ruby
class Status
  attr_accessor :name

  def ==(other)
    other.respond_to?(:name) ? name == other.name : name == other
  end
end
```

**Comment by cupakromer** [comment] 2015-06-16 16:49
@mockdeep you don't need to monkey patch string. You will need to implement `to_str` though. Just be aware that by implementing `to_str` you are telling Ruby that it can usually treat your class as a String. However, normally in when Ruby wants to do that (such as with `==`), it will invert the call and ask your object to respond:

```ruby
Status = Struct.new(:name) do
  def ==(other)
    p("IN CUSTOM ==")
  end
  def to_str
    name
  end
end

submitted = Status.new('submitted')
submitted == 'submitted'
# "IN CUSTOM =="
# => "IN CUSTOM =="

'submitted' == submitted
# "IN CUSTOM =="
# => true
```

I have not audited the behavior too deeply so actual milage may very.

**Comment by mockdeep** [comment] 2015-06-16 17:35
Thanks, I'll give that a try. After thinking about it some more, though, I don't really agree with the idea that `==` needs to always be symmetric (or that RSpec should be enforcing it). In this case, saying `'submitted' == status` seems a little like saying "doctor is a Bob". It's a little unintuitive also to have to know that RSpec is going to compare things in the reverse order of what you specify.

**Comment by myronmarston** [comment] 2015-06-16 17:53
> Thanks, I'll give that a try. After thinking about it some more, though, I don't really agree with the idea that == needs to always be symmetric (or that RSpec should be enforcing it).

I suppose we could check `==` both ways, but it's been shown by multiple user reports that calling `==` on the `actual` object can and does lead to errors that users report back to us and expect us to work around or avoid.  We're trying to please everyone but I don't know if we can here :(.

> It's a little unintuitive also to have to know that RSpec is going to compare things in the reverse order of what you specify.

Why do you find it unintuitive?  The objects passed to the matcher are the things you've provided as the standard of comparison....so doesn't it make more sense for us to check with them?  Other users have argued in favor of this, because they found it unintuitive in RSpec 3.0...3.2 that we used the `actual` object as the standard of comparison rather than `expected`.  For example, see rspec/rspec-mocks#730:

> There are several things wrong with this.

> First, we are invoking `==` on `actual`. This is not the matcher, it is the value being matched, and we should not be consulting it on the topic of it being equal to a matcher. Equality should always be decided by the value _in_ the test, not the value _under_ test.

So I've got some users telling me that `actual == expected` is unintuitive and they'd expect `expected == actual`, and I've got you telling me the opposite.  I believe RSpec 2 always checked `expected == actual` and no one ever complained (that I know of).

Meanwhile, we've got others users that have defined `==` so that `actual == expected` raises errors when `expected` is not of the same class.

I'm still of the opinion that `==` should be symmetric, and objects that violate this are fundamentally busted, hard to reason about and lead to all sorts of surprises.  Still, I'm open to doing whatever we can reasonably do to smooth this out for users...but it's not clear to me what that would be, given all the history above.

Bear in mind that `==` has a very specific meaning (value equality) and it doesn't make sense to me to say that a string is equal to an instance of `Status`.  Ruby has other operators (such as `===`) that are meant to support "loose matching" rather than strict value equality.  Is there any reason you can't use `===` for your case since it looks to me like "matching" is really what you are going for?

**Comment by mockdeep** [comment] 2015-06-16 18:30
> it's been shown by multiple user reports that calling == on the actual object can and does lead to errors that users report back to us and expect us to work around or avoid.

This is understandable. I don't really have a good solution to the problem. Is there no way you could detect this sort of error and give the user a more meaningful message?

> Why do you find it unintuitive?

To me this is unintuitive because when I write `expect(a).to eq(b)` I expect it to evaluate `a == b`, in the order it's read. It's confusing to me to occasionally bump up against it and have to realize that, oh yeah, RSpec compares it the other way. I remember that from RSpec 2 and always felt it was a little odd.

> I'm still of the opinion that == should be symmetric, and objects that violate this are fundamentally busted, hard to reason about and lead to all sorts of surprises.

I understand the motivation for wanting it to be symmetrical, though I disagree that it is "fundamentally busted" if not, and don't really think it's the place for RSpec to try to enforce it. And, in fact, as far as I can tell swapping the order is just inverting the problem. Instead of making sure `a` has defined `#==`, we're just making sure `b` has defined `#==`.

> Is there any reason you can't use === for your case since it looks to me like "matching" is really what you are going for?

That does seem more "proper" but in our case we'd like for our `Status` class to be able to transparently drop in in place of a string without actually needing to be too aware that it has some additional functionality under the hood. If we use `===` instead, we end up trying `==` by default, wonder why it's not doing what we expect, then remember, oh yeah, it's actually this `Status` object and I have to use that infrequently seen `===` operator for some reason.

**Comment by cupakromer** [comment] 2015-06-16 18:58
> That does seem more "proper" but in our case we'd like for our Status class to be able to transparently drop in in place of a string without actually needing to be too aware that it has some additional functionality under the hood...we end up trying `==` by default, wonder why it's not doing what we expect, then remember, oh yeah, it's actually this `Status` object

I would think in this case it would be important for them to be symmetric. For exactly the case you mention. It would be easy to have an actual string stored in a variable in some other part of the code, then do something like: `display_status == status` where `status` is a `Status`; which would fail. You would have to explicitly know that `status` wasn't actually a string and be sure you always do `status == any_other_variable`.

**Comment by cupakromer** [comment] 2015-06-16 19:06
Another example which would be surprising without symmetry:

```ruby
Status = Struct.new(:name) do
  def ==(other)
    other.respond_to?(:name) ? name == other.name : name == other
  end
end

status = 'foo'
case status
when 'foo'
  :equal
else
  :nope
end
# => :equal

status = Status.new('foo')
status == 'foo'
# => true

case status
when 'foo'
  'equal'
else
  'nope'
end
# => :nope
```

**Comment by mockdeep** [comment] 2015-06-16 19:43
True, though those aren't the sorts of use-cases we're likely to come across. It's unlikely we're going to have a status string in a variable, and semantically it seems like `status` is always going to come first in equality operations. If it becomes a necessity, though, we can always monkey patch `String` at the time.

For case equality we can still define the `===` operator and have it work transparently. There's nothing keeping us from having both interfaces work transparently, but again, that's something we can address when it comes up, which may never happen. We're more likely to use a map, which will require converting to a string or symbol either way.

**Comment by cupakromer** [comment] 2015-06-16 20:59
Unfortunately, case equality won't work transparently :crying_cat_face:. While the default implementation of `===` for most objects is `==`, Ruby treats case statements as `case_match === obj` not `obj === case_match`. So even implementing a custom `Status#===` won't make it work, as the expression will be `'test' === status`:

```ruby
status = Status.new('test')
status === 'test'
# => true

'test' === status
# => false

case status
when 'test'
  :match
else
  :nope
end
# => :nope
```

You know your code base and usage the best. Speaking from my own experience, non-symmetric equality with _core_ types can lead to lots of unexpected pain later. I pointed out the case-statement issue simply because it has been a problem for me, as it's my default pattern for cleaning up several `if`, `elsif`, statements.

I know having to write your own custom matcher for this case is frustrating. Personally I think it could help convey the non-symmetric properties of the object:

```ruby
RSpec::Matchers.define :represent do |expected|
  match do |actual|
    actual == expected
  end
end
```

**Comment by mockdeep** [comment] 2015-06-16 21:04
> Personally I think it could help convey the non-symmetric properties of the object

Yeah, the problem in our case is that we're trying to test the change in status:

```ruby
expect {
  # do something
}.to change(object.status).from('viewed').to('submitted')
```

**Comment by myronmarston** [comment] 2015-06-16 21:08
Composable matchers have got your back:

``` ruby
RSpec::Matchers.define :an_object_representing do |expected|
  match do |actual|
    actual == expected
  end
end

expect {
  # do something
}.to change(object.status).from(an_object_representing 'viewed').to(an_object_representing 'submitted')
```

**Comment by mockdeep** [comment] 2015-06-16 22:06
That seems like a lot of workaround. I think we'll just monkey patch `String` for now. We also got bit by the `DelegateClass` issue above. We have a `FieldDecorator` class that gets used in one context and when stubbing:

```ruby
allow(obj).to receive(:my_method)
obj.do_something
expect(obj).to have_received(:my_method).with(my_field)
# fails because it actually got called with a decorator
```

We end up having to patch this up in the `FieldDecorator` for the sake of the tests even though it's not something that is likely to ever come up in our code.

**Comment by mockdeep** [comment] 2015-06-16 22:13
I ended up resolving it by adding `delegate :instance_of?, to: :__getobj__` to `FieldDecorator`.
