### ISSUE TITLE
Facing issues in executing different spec files in desired order with rspec

### ISSUE THREAD

**Issue by chandanaGollapudi** [rspec/rspec-core#1899] opened 2015-03-12 11:13 UTC
Hi ,

I am recently started using ruby and rspec. I am facing some issue in executing different spec files with rspec in desired order. tests are executing  is in alphabetical order . But I would like to execute tests in the order provided by user.

Initially i tried using rake,but going through several post came to know the best way to this through rpsec and there are several options to do that and rspec won't  consider order that has given in CLI . As per my understanding we can use"order_groups" for this.

Could someone help me in finding solution for this and  elaborate on how to implemention?

**Comment by myronmarston** [comment] 2015-03-12 14:33
Duplicate of #1900.

**Closed by myronmarston** 2015-03-12 14:33 UTC

**Comment by chandanaGollapudi** [comment] 2015-03-13 14:17
thanks your quick response.I have gone through link that you suggested.i have few clarifications on below provided code.
Could you please provide your answers on below points.

1.In which file i need to add this code( is it spec_helper.rb or new spec file)?
  1.1 if it is spec_helper,now different scrum team using same spec_helper file. will it affect others execution,if so how to handle it?
  
  1.2 iam planning to create new spec file and add below code to that.will it execute all other spec files in desired order by running new spec?
  
2. what is the significance of numerics in below code? as per my understaning groups execution order will be based on tags and the order will be feature,request and model.

RSpec.configure do |config|
  config.register_ordering(:global) do |items|
    items.sort_by do |group|
      case group.metadata[:type]
      when :feature then 50
      when :request then 40
      when :model   then 10
      else 20
      end
    end
  end
end
