### ISSUE TITLE
Crash when let/! referencing an undefined variable

### ISSUE THREAD

**Issue by david50407** [rspec/rspec-core#2120] opened 2015-11-21 12:40 UTC
When I using Rspec with let! method like this code: 

```
let!(:time_begin) { time_base.beginning_of_day } # pointed to undefined target `time_base`
```

It crash Ruby interpreter...and I got this error:

https://gist.github.com/david50407/6bca64af09e9c1a6663a

This is like this bug: https://bugs.ruby-lang.org/journals/diff/49846?detail_id=35978

**Comment by samphippen** [comment] 2015-11-21 17:46
Which version of RSpec and Ruby are you running? Is this within a Rails application?

I cannot reproduce this against RSpec master with the details you provided, instead getting this error message:

```
       undefined local variable or method `variable_inside_let_bang' for #<RSpec::ExampleGroups::Anonymous::Anonymous:0x007facfaae39c8>
```

**Comment by myronmarston** [comment] 2015-11-21 18:13
> Which version of RSpec and Ruby are you running?

rspec-core 3.2.3 and ruby 2.2.1, according to the gist :smile: 

> Is this within a Rails application?

There are rspec-rails stack frames in the gist, so it appears so.

Regardless -- segfaults in pure ruby libraries generally indicate bugs in ruby (although the library may hit some pathalogical case in ruby that triggers it and could perhaps work around it).  You're the only one to report this, though, so it doesn't appear to be widespread.

**Comment by david50407** [comment] 2015-11-22 07:26
Ruby 2.2.1p85 and rspec-core 3.2.3 running with Rails 4.2.0 on Ubuntu 14.04.2 x64.

Maybe I'll try other version of ruby, thanks

**Comment by samphippen** [comment] 2015-11-22 13:11
I've tried to reproduce this with those exact versions and couldn't (on a slightly different version of ubuntu). Most of the time, this is a cpu/compiler-specific bug in ruby (according to a conversation I once had with nobu) and therefore not our problem. @david50407 I'd suggest filing this against ruby (if you haven't already), I'm going to close it against RSpec for now.

If somebody else finds this in the wild specifically against RSpec again. We'll re-open and de-duplicate the issues.

**Closed by samphippen** 2015-11-22 13:11 UTC
