### ISSUE TITLE
With --bisect, display tests in the final output according to their execution order

### ISSUE THREAD

**Issue by aprescott** [rspec/rspec-core#2001] opened 2015-06-17 18:36 UTC
The new `--bisect` feature is genuinely fantastic. So, first, huge thank you to all involved in making it!

I recently used `--seed <seed> --fail-fast --bisect=verbose` to hunt down an order-dependent test failure. It left me with two tests, and outputted something like this for a reproduction command:

``` shell
rspec ./spec/lib/foo.rb[1:3:1] ./spec/lib/tasks/bar.rb[1:1:3:1] --seed 61008 --fail-fast
```

These two tests were indeed causing problems when run together. However, when running this command, the actual ordering of the test execution was:
1. `bar.rb[1:1:3:1]`
2. `foo.rb[1:3:1]`

I think it'd be great if the result of `--bisect` would make it clear that this is actually the ordering. Right now, the reproduction command is _suggested_ as `foo.rb` _then_ `bar.rb`. With only 2 examples to work with, this isn't a huge deal, because you can infer which is going first based on which of them fails. But with 3 or 4, it might get confusing.

Perhaps this is a case of just ordering the tests in the repro output? Potentially this could be called out directly? I think this would be useful even if it's a non-`verbose` `--bisect`.

**Comment by myronmarston** [comment] 2015-06-17 19:31
This is a great idea.  I'm in favor of it.

One potential complexity with this: we try to minimize the length of the reproduction command by merging multiple ids from the same file so that you get this:

``` ruby
rspec ./spec/lib/foo.rb[1:3:1,1:4:1] ./spec/lib/bar.rb[1:4:1]
```

...rather than this:

``` ruby
rspec ./spec/lib/foo.rb[1:3:1] ./spec/lib/foo.rb[1:4:1] ./spec/lib/bar.rb[1:4:1]
```

The logic that merges ids to create the shorter repro command would have to be smart enough to order the ids within the list for a file, and also to only merge them when they are adjacent.  One file can have multiple top-level example groups which means that you could have some specs from `./spec/lib/foo.rb` run followed by some specs from `./spec/lib/bar.rb` followed by some more specs from `./spec/lib/foo.rb`.  In such a situation, the ids from the first `foo` set and last `foo` set should not be merged if we want to maintain the behavior that the repro command lists the ids in order.

Want to take a stab at this?

Bear in mind that @urbanautomaton is working on some bisect improvements in #1997 so there's the potential for merge conflicts right now if you work on some bisect changes.

**Comment by urbanautomaton** [comment] 2015-06-18 10:28
Thanks for the heads-up - at the moment I don't think any of my stuff will touch `Bisect::Runner`, so I'd hope that any changes to the repro command formatting would merge cleanly with my changes. Any conflicts would be in the tests that check formatter output, and I think they'd be minor.

**Comment by xaviershay** [comment] 2017-01-15 19:04
Note that #1997 is merged so no risk of conflicts.

I think I'm slightly negative on this change. If I understand you correctly, the repro command still repros fine with correct ordering, but you're looking to instead infer the order from the command line arguments. That seems to me a) a dangerous precedent and likely to create inconsistencies, and b) not worth the extra complexity of minimizing correctly.

Since this is also old, I'm going to close this as stale. @myronmarston feel free to reopen if you think it really is desirable, or @urbanautomaton if you had a PR.

**Closed by xaviershay** 2017-01-15 19:04 UTC

**Comment by urbanautomaton** [comment] 2017-01-15 19:36
I don't have a PR, and I think I agree with the reasons given for not proceeding with this. The command-line args (excluding flags) don't directly imply the execution order, so if we want to make it easy for users to discover the execution order, we should find a way to nudge them towards using the documentation formatter rather than making non-semantic changes to the repro output.
