### ISSUE TITLE
Test is not a class (TypeError)

### ISSUE THREAD

**Issue by zedtux** [rspec/rspec-core#1859] opened 2015-02-02 07:02 UTC
As discussed with @myronmarston on Twitter:

![screen shot 2015-02-02 at 08 00 15](https://cloud.githubusercontent.com/assets/478564/5996848/923f5c8a-aab1-11e4-9707-b1e8a8228bf3.png)

RSpec doesn't allow us to have a class named **Test** while it should:

    app/models/test.rb:6:in `<top (required)>': Test is not a class (TypeError)
      from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
      from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
      from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
      from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
      from /cursus-scholar/application/spec/models/test_spec.rb:2:in `<top (required)>'
      from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
      from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
      from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
      from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
      from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
      from /usr/local/bin/rspec:23:in `load'
      from /usr/local/bin/rspec:23:in `<main>'

**Comment by myronmarston** [comment] 2015-02-02 07:12
Can you paste the contents of your `app/models/test.rb` file?

**Comment by JonRowe** [comment] 2015-02-02 10:24
This has all the hall marks of Rails autoloading being a pain in the proverbial...

**Comment by cupakromer** [comment] 2015-02-02 17:31
I've reproduced this. Here's a simple working spec with _only_ RSpec:

```ruby
class Test; end

RSpec.describe Test do
  it "works" do
    expect(described_class).to be Test
  end
end
```

Now if I put that in a Rails project (I was using Rails 4.0 and Ruby 2.2 when I tested) and load `require 'rails_helper'` at the top you get the stack trace:

```
/example_app/spec/test_spec.rb:3:in `<top (required)>': Test is not a class (TypeError)
	from /rspec-core/lib/rspec/core/configuration.rb:1200:in `load'
	from /rspec-core/lib/rspec/core/configuration.rb:1200:in `block in load_spec_files'
	from /rspec-core/lib/rspec/core/configuration.rb:1198:in `each'
	from /rspec-core/lib/rspec/core/configuration.rb:1198:in `load_spec_files'
	from /rspec-core/lib/rspec/core/runner.rb:97:in `setup'
	from /rspec-core/lib/rspec/core/runner.rb:85:in `run'
	from /rspec-core/lib/rspec/core/runner.rb:70:in `run'
	from /rspec-core/lib/rspec/core/runner.rb:38:in `invoke'
	from /rspec-core/exe/rspec:4:in `<top (required)>'
	from bin/rspec:16:in `load'
	from bin/rspec:16:in `<main>'
```

This is failing before it even runs the test. It fails on the line `class Test; end`. This is happening because `Test` is already defined and it's a module. It's coming from `Test::Unit`.

**Comment by cupakromer** [comment] 2015-02-02 17:36
@zedtux what is your Rails version and your Ruby version?

**Comment by cupakromer** [comment] 2015-02-02 17:49
Flipping the loading for Rails and rspec-rails with the `Test` class definition it seems rspec-rails raises the same error (since `Test` is already defined as a class) in [`lib/rspec/rails/matchers.rb`](https://github.com/rspec/rspec-rails/blob/b1ceb0cd0a/lib/rspec/rails/matchers.rb#L15):

```ruby
begin
  require 'test/unit/assertionfailederror'
rescue LoadError
  module Test
    module Unit
      class AssertionFailedError < StandardError
      end
    end
  end
end
```

I'll move this to rspec-rails, but I'm not sure what a fix would entail, or if it's even possible, yet.

**Comment by cupakromer** [comment] 2015-02-02 17:53
Closing and will track via rspec/rspec-rails#1294

**Closed by cupakromer** 2015-02-02 17:53 UTC

**Comment by zedtux** [comment] 2015-02-03 04:25
> @zedtux what is your Rails version and your Ruby version?

Rails 4.2 and Ruby 2.2

Thank you @cupakromer for your help !
