### ISSUE TITLE
RSpec::Core::Runner.run on a broken file poisons the world

### ISSUE THREAD

**Issue by kwerle** [rspec/rspec-core#2666] opened 2019-10-12 00:03 UTC
### Subject of the issue
RSpec::Core::Runner.run on a broken file (unresolved symbols) will make further executions of RSpec::Core::Runner.run fail.

The expectation is that running it on a broken file and then on a valid file should generate the correct output for the valid file.

### Your environment
* Ruby version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
* rspec-core version: rspec (3.9.0)

### Steps to reproduce
Please see https://github.com/kwerle/broken_rspec for a trivial project with an example.

In essence:
```
RSpec::Core::Runner.run(['path_to_broken_file.rb'])
RSpec::Core::Runner.run(['path_to_valid_file.rb'])
```
produces only the results from the broken file, not the valid file.  Reversing those two calls behaves as expected.  Adding any calls after a broken file will essentially fail.

### Expected behavior
Because this is a class method, I expect calls after a broken file to work as if they were without being preceeded by a broken file.

### Actual behavior
Calls after a broken file do not work.

**Comment by pirj** [comment] 2019-10-13 14:52
I suspect it's due to "out of spec failures", and normally, say when you run
```sh
rspec test_specs
```
in the reproduction project you provided, it would finish with:
```
0 examples, 0 failures, 1 error occurred outside of examples
```
This is because they are parsed all at once, and out of example error is detected before examples are being run.

When you point `RSpec::Core::Runner.run` to a single spec file, it loads that one specific file and runs examples. Once it stumbles across an outside-of-example error, it stops.

Honestly, I don't see any inconsistency here.

If you are building a tool on top of RSpec, I suggest you set:
```ruby
any_non_example_failures ||= RSpec.world.non_example_failure
RSpec.world.non_example_failure = false
```
between `RSpec::Core::Runner.run` calls, and assign it back before signalling your formatters to print out the footer.

Another way is to use the lower-level code:
```ruby
RSpec.configuration.reporter.report(10000) do
  TEST_FILES.each do |path|
    RSpec.world.example_groups.clear
    options = RSpec::Core::ConfigurationOptions.new([path])
    options.configure(RSpec.configuration)
    RSpec.configuration.load_spec_files
    RSpec.world.ordered_example_groups.each { |example_group| example_group.run(RSpec.configuration.reporter) }
  end
end
```

**Comment by kwerle** [comment] 2019-10-13 22:47
I really appreciate your solution and will give it a shot.

But it really seems to me that `.run` should probably `RSpec.world.non_example_failure = false` at the top of the method.  I would find that least surprising.

**Comment by kwerle** [comment] 2019-10-14 15:28
I've modified my trivial code like so:

```
def run_file(file)
  RSpec.world.example_groups.clear
  RSpec::Core::Runner.run([file])
  any_non_example_failures ||= RSpec.world.non_example_failure
  puts 'any_non_example_failures!' if any_non_example_failures
  RSpec.world.non_example_failure = false
end
```

This does clear the `RSpec.world.non_example_failure`, but it still does not allow running of additional files.  Of interest, following calls continue to print that there was an error outside of tests after setting non_example_failure false.

**Comment by JonRowe** [comment] 2019-10-14 16:25
:wave: So RSpec is not designed to have `RSpec::Core::Runner.run` called multiple times, as we are primarily a command line tool theres a bunch of things that don't quite gel when used programatically, although we are open to do improving things if possible.

In particular here you might want to look at the docs for [`RSpec::Core.reset`](http://rspec.info/documentation/3.9/rspec-core/RSpec.html#reset-class_method).

Of relevance particularly:

> Users must invoke this if they want to have the configuration reset when they use the runner multiple times within the same process. Users must deal themselves with re-configuration of RSpec before run.

If you are set on messing with the world directly you will also note theres a `World#reset` method that does a similar function but doesn't reset any of the "in flight" data, but this is a private API.

**Closed** 2019-10-14 16:26 UTC

**Comment by JonRowe** [comment] 2019-10-14 16:27
I'm closing this only because I believe this is a "behaving as designed" issue, I am happy to continue the discussion here and re-open / raise a new issue if there is something we can change here. Although I do not want to change the current `non_example_failure` default :)

**Comment by kwerle** [comment] 2019-10-14 16:30
Thank you.  I'll take this for a spin.

Offhand, it seem like `RSpec::Core::Runner.run` ought to call `RSpec::Core.reset` itself.  That's what `.run` smells like: "I want to do a single run in a fresh world."

**Comment by kwerle** [comment] 2019-10-14 16:36
Oh - it's actually `RSpec.reset`, and it does appear to do what I want.

I'll consider this a functional workaround.  But as I said at the top, a full reset at the top of the `.run` method would be least surprising to me.

**Comment by JonRowe** [comment] 2019-10-14 16:39
Well if you initialise `RSpec::Core::Runner` yourself you get to choose that behaviour, I'll stress again the API is designed primarily for our usage and we always create a new instance but with the shared globals on startup. Theres no reason why you can't inject new instances each time.
