### ISSUE TITLE
GitHub Actions, Windows

### ISSUE THREAD

**Issue by MSP-Greg** [rspec/rspec-core#2724] opened 2020-04-26 16:36 UTC
Wondering if there's interest in running any CI on GitHub Actions.  It supports MRI Ruby 2.2 and later on Ubuntu, macOS, & Windows.  JRuby & TruffleRuby are also available.

For an example run, see:
https://github.com/MSP-Greg/rspec-core/actions/runs/88352990

yaml script is at:
https://github.com/MSP-Greg/rspec-core/blob/actions-windows/.github/workflows/rspec-core.yml

There are a few issues on Windows that could be updated, all are test/spec issues, not 'lib' code issues.

**Comment by JonRowe** [comment] 2020-04-26 16:41
Yes there is interest. Its something I've been considering and I think @benoittgt has looked into a bit. 

We'd consider having `rspec-rails` move over first as it only supports modern Rubies and doesn't have windows builds, but eventually I like the idea of having all the CI on Github with a matrix of modern rubies on linux and windows at least.

We would have to keep some Travis builds until RSpec 4 due to needing older Ruby support such as `1.8.7`, but we could have "legacy builds" only there.

**Comment by MSP-Greg** [comment] 2020-04-26 17:05
> but we could have "legacy builds" only there

Probably a good idea to continue with "legacy builds" on both AppVeyor & Travis.  Some repos keep all their 'allow failure' jobs there also.

Re Windows, I can't remember Win7 & 8 or Vista very well, but Windows consoles have worked with ANSI escape/color codes for quite a while.  Windows supports spaces & single quotes (apostrophe)  in filenames, but it does not support a standard double quote.  I haven't tried unicode quotes.

Anyway, if you want me to do anything, let me know.  Feel free to close.

**Comment by benoittgt** [comment] 2020-04-26 18:06
Thanks a lot @MSP-Greg for the help offer.

I looked a it https://github.com/rspec/rspec-dev/issues/234 and ended up stopping for a moment because I had too many side issues when testing with Github Actions. The cost of change was too big. 

I thought the switch would have been easier. I tried only rspec-core and it was already many surprises and issue open in other open-source repo, like https://github.com/actions/virtual-environments/issues/267. I ended up with a complicated error that I was no able to reproduce locally, I tried two hours, then drop. :/

To be honest, I thought: What will be the major gain to switch? I read that other smaller ruby lib like rom switched to Github actions and enjoyed the fast boot, but in our case rspec is different, little bigger, bigger build matrix.

**Comment by MSP-Greg** [comment] 2020-04-27 00:21
I started with the AppVeyor script, and added the Unbuntu & macOS jobs.

I now see that the Travis script does a lot more than the AppVeyor script.

A lot has changed with Actions, but if you're auto-generating all your CI scripts/yaml, changing to Actions is more involved...

**Comment by JonRowe** [comment] 2020-04-27 08:58
Whilst they say they are auto-generated, what they mean is they are copies of those in `scripts` in `rspec-dev` this is done to keep them in sync. (Its a lot easier to run a rake task to update them than to copy pasta each time we make a change etc).

**Comment by pirj** [comment] 2020-12-24 12:38
This is done, closing.
https://github.com/rspec/rspec-core/blob/addcfb47cb0582b8e976c938ff18728144a7dcee/.github/workflows/ci.yml#L68

**Closed by pirj** 2020-12-24 12:38 UTC
