### ISSUE TITLE
Appveyor build fails on html_formatter_spec.rb:98 (Windows and Ruby 2.0 only)

### ISSUE THREAD

**Issue by rsanchez79** [rspec/rspec-core#1868] opened 2015-02-05 23:29 UTC
This issue seems to be related to nokogiri on windows. The expected html file shows the charset=utf-8 but we are getting charset=IBM437. I believe this is causing issues with empty space on below image.

![characterset](https://cloud.githubusercontent.com/assets/585956/6071443/7ec83328-ad5b-11e4-983b-5b61c7b75df0.PNG)

**Comment by myronmarston** [comment] 2015-02-06 06:36
If the failure is due to a bug in nokogiri, not a bug in RSpec, then maybe it's best to skip that spec on Ruby 2.0 on windows?  Thoughts?

**Comment by JonRowe** [comment] 2015-02-06 12:37
:+1:

**Comment by samphippen** [comment] 2015-12-11 09:26
Can we close this now?

**Comment by JonRowe** [comment] 2015-12-11 11:13
Seems legit

**Closed** 2015-12-11 11:13 UTC
