### ISSUE TITLE
Windows doesn't support chinese sample

### ISSUE THREAD

**Issue by WoolenWang** [rspec/rspec-core#2660] opened 2019-07-17 10:16 UTC
```
Run options: include {:full_description=>/AGENT::Services::CLI\ �첽������\��python������Ŀ����/}
	from D:/tools/atr/sft_tool/mingw32/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.1/lib/rspec/core/world.rb:182:in `announce_filters'
	from D:/tools/atr/sft_tool/mingw32/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.1/lib/rspec/core/runner.rb:99:in `setup'
	from D:/tools/atr/sft_tool/mingw32/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.1/lib/rspec/core/runner.rb:86:in `run'
	from D:/tools/atr/sft_tool/mingw32/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.1/lib/rspec/core/runner.rb:71:in `run'
	from D:/tools/atr/sft_tool/mingw32/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.1/lib/rspec/core/runner.rb:45:in `invoke'
	from D:/tools/atr/sft_tool/mingw32/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.1/exe/rspec:4:in `<top (required)>'
	from D:/tools/atr/sft_tool/mingw32/bin/rspec:23:in `load'
	from D:/tools/atr/sft_tool/mingw32/bin/rspec:23:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by pirj** [comment] 2020-01-15 18:23
@WoolenWang Can you figure out the difference between the code @benoittgt provided and yours to understand why yours fails and the script provided provides correct output?

A pull request that fails on AppVeyor would sure be very helpful.

I'll close the issue meanwhile, since otherwise it's not clear how to reproduce the problem and how to fix it. Please feel free to reopen.

**Comment by JonRowe** [comment] 2020-01-15 20:01
The problem's pretty clear, Chinese string's being passed in from the command line on windows are not being parsed properly, the issue I, we, have is trying to replicate it to fix it, ideally we need a chinese person to help!

**Comment by JonRowe** [comment] 2024-11-27 20:04
Closing due to inactivity, we don't have anyone Chinese to help.

**Closed by JonRowe** 2024-11-27 20:04 UTC
