### ISSUE TITLE
CLI support for rerunning tests

### ISSUE THREAD

**Issue by NB28VT** [rspec/rspec-core#1852] opened 2015-01-20 15:33 UTC
It would be great to have an Rspec tag for running one test multiple times from the command line. Right now I'm using the "for i in 'seq 50'; do rspec spec" command UNIX provides in the CLI. Thank you

**Comment by JonRowe** [comment] 2015-01-20 22:57
Duplicate of #795, this is better off as an extension or simply using the UNIX script you provided.

**Closed by JonRowe** 2015-01-20 22:57 UTC
