### ISSUE TITLE
--bisect's ShellRunner does not properly shellescape special characters

### ISSUE THREAD

**Issue by DavidS** [rspec/rspec-core#2638] opened 2019-06-13 13:49 UTC
### --bisect's  ShellRunner does not properly shellescape special characters

when running `rspec --bisect` `Open3.capture2e` called at
https://github.com/rspec/rspec-core/blob/2800fe118fa2efeb87b7bdc7888476373debf6ca/lib/rspec/core/bisect/shell_runner.rb#L48 will pass the `cmd` string through to the system shell without any escaping, leading to spurious failures.

### Your environment
* Ruby version: 2.5.5
* rspec-core version: 3.8.0

### Steps to reproduce

Execute `rspec --bisect --pattern 'spec/**{,/*/**}/*_spec.rb' --exclude-pattern 'spec/{fixtures/**/*.rb,fixtures/modules/*/**/*.rb}'` with active shell backend

### Expected behavior

The provided pattern and exclude patterns should be passed through unchanged to the shelled out processes.

### Actual behavior

The provided patterns get exposed to the system shell and cause spurious failures. If I `puts cmd.inspect` just before L48 (see above) I get this:

```
"[...] --pattern spec/**{,/*/**}/*_spec.rb --exclude-pattern spec/{fixtures/**/*.rb,fixtures/modules/*/**/*.rb}"
```

and a lot of failures from the --exclude-pattern being wrong.

**Comment by benoittgt** [comment] 2019-06-23 10:08
Hello

Thank for this issue. I think my knowledge on this one are quite limited.

Do you think you can provide a reproducing example with "spurious failures"?

Sorry to ping you @myronmarston but maybe you have an idea?

**Comment by JonRowe** [comment] 2019-06-23 10:11
:wave: @benoittgt this is on my list to tackle, it will just be that we're not properly escaping / passing the pattern to the shell, its known to be problematic due to the fact that various glob characters are treated specially by terminal shells, and we need the "glob string" and not the expanded glob. It's a similar issue to what happens with Rake.

**Comment by benoittgt** [comment] 2019-06-23 10:16
Ok. Thanks Jon! :)

**Comment by JonRowe** [comment] 2019-06-23 16:28
Hm, ok, this is slightly more complex than I realised... We are having to parse the original cli and then re output it, but we are correctly escaping the shell output on my system. What OS and Ruby engine are you using @DavidS ?

**Comment by DavidS** [comment] 2019-06-24 08:58
Debian testing and it's system ruby (2.5.5 at the moment)

**Comment by DavidS** [comment] 2019-06-24 11:02
@JonRowe can you point me at where the escaping is happening? maybe I was looking at the wrong bit when debugging...

**Comment by JonRowe** [comment] 2019-06-24 11:03
Can you give #2643 a go to see if it solves your issue?

**Comment by DavidS** [comment] 2019-06-24 15:55
Much to my embarrassment I have to say I haven't been able to repro this issue after giving it a few tries this afternoon.

**Comment by JonRowe** [comment] 2019-06-29 11:01
I can't replicate it either now, previously I had files failing but escaping them on input works fine, without a reproduction I'm not sure I want to merge #2643

**Comment by myronmarston** [comment] 2019-06-29 17:03
Can you use the `ForkRunner` instead of the `ShellRunner`?  It's generally faster (in some cases, significantly so) and shouldn't have this problem (it never shells out).

**Comment by JonRowe** [comment] 2019-06-29 17:53
@myronmarston the linked issue explains why shell runner was used at all,
the OP ran into a deadlock with the fork runner

**Comment by JonRowe** [comment] 2024-11-27 19:58
I'm going to close this, its been a while and I don't think there was a good reproduction

**Closed by JonRowe** 2024-11-27 19:58 UTC
